/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    orders: Order;
    consultations: Consultation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    consultations: ConsultationsSelect<false> | ConsultationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    hero: Hero;
    problem: Problem;
    manifesto: Manifesto;
    marquee: Marquee;
    'how-it-works': HowItWork;
    'before-afters': BeforeAfter;
    pricing: Pricing;
    reviews: Review;
    team: Team;
    proof: Proof;
    movers: Mover;
    cta: Cta;
    faqs: Faq;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    problem: ProblemSelect<false> | ProblemSelect<true>;
    manifesto: ManifestoSelect<false> | ManifestoSelect<true>;
    marquee: MarqueeSelect<false> | MarqueeSelect<true>;
    'how-it-works': HowItWorksSelect<false> | HowItWorksSelect<true>;
    'before-afters': BeforeAftersSelect<false> | BeforeAftersSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    proof: ProofSelect<false> | ProofSelect<true>;
    movers: MoversSelect<false> | MoversSelect<true>;
    cta: CtaSelect<false> | CtaSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * People who can sign in and edit the Moves site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the admin bar and on activity.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Upload and manage all photos and videos for the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO. Leave blank for purely decorative images.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Treatment plans and add-ons available to order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Shown to patients, e.g. "Moves Full".
   */
  name: string;
  /**
   * URL-safe id. Leave blank to derive from the name.
   */
  slug?: string | null;
  /**
   * Integer pence — 240000 is £2,400. Money is never stored as a float; rounding errors compound across a ledger.
   */
  pricePence: number;
  /**
   * Short summary shown on the pricing card.
   */
  description?: string | null;
  /**
   * Unticked products stay in past orders but cannot be ordered again.
   */
  active?: boolean | null;
  /**
   * Optional product image.
   */
  image?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Treatment plans ordered by patients.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Human-facing order number. Auto-generated if left blank.
   */
  reference?: string | null;
  patientName: string;
  patientEmail: string;
  patientPhone?: string | null;
  /**
   * Which treatment plan was ordered.
   */
  product: number | Product;
  /**
   * Copied from the product at order time, then frozen. A later price change must not rewrite historic orders.
   */
  amountPence: number;
  status: 'placed' | 'in_production' | 'shipped' | 'delivered' | 'cancelled';
  /**
   * Treating GDC-registered dentist.
   */
  dentist?: string | null;
  clinic?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Consultations booked through the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultations".
 */
export interface Consultation {
  id: number;
  patientName: string;
  email: string;
  phone?: string | null;
  scheduledFor: string;
  clinic?: string | null;
  dentist?: string | null;
  status: 'upcoming' | 'completed' | 'no_show' | 'cancelled';
  /**
   * Where the booking came from — Website, Instagram, Referral…
   */
  source?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'consultations';
        value: number | Consultation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  pricePence?: T;
  description?: T;
  active?: T;
  image?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  reference?: T;
  patientName?: T;
  patientEmail?: T;
  patientPhone?: T;
  product?: T;
  amountPence?: T;
  status?: T;
  dentist?: T;
  clinic?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultations_select".
 */
export interface ConsultationsSelect<T extends boolean = true> {
  patientName?: T;
  email?: T;
  phone?: T;
  scheduledFor?: T;
  clinic?: T;
  dentist?: T;
  status?: T;
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The top announcement bar and the navigation. Mobile shows different copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  announcementNote?: string | null;
  announcementLink?: string | null;
  /**
   * Shown instead of the desktop message on small screens.
   */
  announcementMobile?: string | null;
  logo?: (number | null) | Media;
  /**
   * Shown on desktop; collapse into the mobile menu button.
   */
  navLinks?:
    | {
        label?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  button?: {
    label?: string | null;
    /**
     * Shorter label for small screens, e.g. "Consultation".
     */
    labelMobile?: string | null;
    href?: string | null;
  };
  showCart?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The pink hero: rating, headline, CTA and portrait.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  /**
   * e.g. "Excellent (3,890)"
   */
  ratingCount?: string | null;
  /**
   * The coral part + the rest.
   */
  headline?: {
    accent?: string | null;
    rest?: string | null;
  };
  subhead?: string | null;
  primaryButton?: {
    label?: string | null;
    /**
     * Where it links — a URL or an on-page anchor like #cta.
     */
    href?: string | null;
  };
  secondaryLinkLabel?: string | null;
  heroImage?: (number | null) | Media;
  signature?: {
    /**
     * Handwritten name, e.g. "Amelia Hart".
     */
    name?: string | null;
    line1?: string | null;
    line2?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hover-to-swap list of "wrong moves" with images.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problem".
 */
export interface Problem {
  id: number;
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  /**
   * The coloured part renders in coral, the rest in navy.
   */
  heading?: {
    accent?: string | null;
    rest?: string | null;
  };
  /**
   * Each item highlights and swaps the image on hover.
   */
  items?:
    | {
        text?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The coral statement section with the laughing portrait.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto".
 */
export interface Manifesto {
  id: number;
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  /**
   * The bright part shows solid white; the dim part is faded.
   */
  heading?: {
    bright?: string | null;
    dim?: string | null;
  };
  subtext?: string | null;
  button?: {
    label?: string | null;
    /**
     * Where it links — a URL or an on-page anchor like #cta.
     */
    href?: string | null;
  };
  backgroundImage?: (number | null) | Media;
  portrait?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The scrolling row of phrases.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marquee".
 */
export interface Marquee {
  id: number;
  words?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The three-step "You move, in three moves" cards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-it-works".
 */
export interface HowItWork {
  id: number;
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  /**
   * The coloured part renders in coral, the rest in navy.
   */
  heading?: {
    accent?: string | null;
    rest?: string | null;
  };
  subtext?: string | null;
  button?: {
    label?: string | null;
    /**
     * Where it links — a URL or an on-page anchor like #cta.
     */
    href?: string | null;
  };
  steps?:
    | {
        /**
         * e.g. "STEP 01"
         */
        stepLabel?: string | null;
        title?: string | null;
        body?: string | null;
        image?: (number | null) | Media;
        imageOverlay?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The "Real moves. Signed." case-study slider.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-afters".
 */
export interface BeforeAfter {
  id: number;
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  /**
   * The coloured part renders in coral, the rest in navy.
   */
  heading?: {
    accent?: string | null;
    rest?: string | null;
  };
  subtext?: string | null;
  cards?:
    | {
        name?: string | null;
        quote?: string | null;
        signedBy?: string | null;
        /**
         * e.g. "GDC: 251837"
         */
        gdc?: string | null;
        beforeImage?: (number | null) | Media;
        afterImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The "Exactly what Moves costs" plan cards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  /**
   * The coloured part renders in coral, the rest in navy.
   */
  heading?: {
    accent?: string | null;
    rest?: string | null;
  };
  subtext?: string | null;
  plans?:
    | {
        title?: string | null;
        /**
         * e.g. "£16.30"
         */
        price?: string | null;
        /**
         * e.g. "/per month"
         */
        per?: string | null;
        productImage?: (number | null) | Media;
        features?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        buttonLabel?: string | null;
        variant?: ('pink' | 'navy') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The "Don't take our word for it" review wall.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * e.g. "Excellent (3,890)"
   */
  ratingCount?: string | null;
  /**
   * The coloured part renders in coral, the rest in navy.
   */
  heading?: {
    accent?: string | null;
    rest?: string | null;
  };
  viewMoreLabel?: string | null;
  reviews?:
    | {
        author?: string | null;
        /**
         * e.g. "5 hours ago"
         */
        timeAgo?: string | null;
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The "Names behind the smiles" dentist cards.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  /**
   * The coloured part renders in coral, the rest in navy.
   */
  heading?: {
    accent?: string | null;
    rest?: string | null;
  };
  subtext?: string | null;
  button?: {
    label?: string | null;
    /**
     * Where it links — a URL or an on-page anchor like #cta.
     */
    href?: string | null;
  };
  members?:
    | {
        name?: string | null;
        /**
         * e.g. "Moves Verified Dentist"
         */
        role?: string | null;
        /**
         * e.g. "GDC No. 12345"
         */
        gdc?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The "Real smiles, real stories" video tiles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof".
 */
export interface Proof {
  id: number;
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  /**
   * Coral part + navy part (this heading starts coral).
   */
  heading?: {
    accent?: string | null;
    rest?: string | null;
  };
  subtext?: string | null;
  videos?:
    | {
        thumbnail?: (number | null) | Media;
        video?: (number | null) | Media;
        /**
         * External link (YouTube/Vimeo) if not uploading a file.
         */
        videoUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The "You don't buy moves" membership tiers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "movers".
 */
export interface Mover {
  id: number;
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  /**
   * The coloured part renders in coral, the rest in navy.
   */
  heading?: {
    accent?: string | null;
    rest?: string | null;
  };
  subtext?: string | null;
  button?: {
    label?: string | null;
    /**
     * Where it links — a URL or an on-page anchor like #cta.
     */
    href?: string | null;
  };
  tiers?:
    | {
        icon?: (number | null) | Media;
        title?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The full-bleed call-to-action banner + guarantee badge.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta".
 */
export interface Cta {
  id: number;
  title?: string | null;
  subtext?: string | null;
  button?: {
    label?: string | null;
    /**
     * Where it links — a URL or an on-page anchor like #cta.
     */
    href?: string | null;
  };
  backgroundImage?: (number | null) | Media;
  badge?: {
    /**
     * e.g. "Money back"
     */
    topLabel?: string | null;
    /**
     * e.g. "Guarantee"
     */
    midLabel?: string | null;
    /**
     * e.g. "30"
     */
    bigNumber?: string | null;
    /**
     * e.g. "days"
     */
    bottomLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The accordion of frequently asked questions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  /**
   * The coloured part renders in coral, the rest in navy.
   */
  heading?: {
    accent?: string | null;
    rest?: string | null;
  };
  items?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer links, socials, mailing list and wordmark.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navLinks?:
    | {
        label?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform?: ('instagram' | 'tiktok' | 'email') | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  mailingLabel?: string | null;
  emailPlaceholder?: string | null;
  wordmark?: (number | null) | Media;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  announcementNote?: T;
  announcementLink?: T;
  announcementMobile?: T;
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  button?:
    | T
    | {
        label?: T;
        labelMobile?: T;
        href?: T;
      };
  showCart?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  ratingCount?: T;
  headline?:
    | T
    | {
        accent?: T;
        rest?: T;
      };
  subhead?: T;
  primaryButton?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryLinkLabel?: T;
  heroImage?: T;
  signature?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problem_select".
 */
export interface ProblemSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?:
    | T
    | {
        accent?: T;
        rest?: T;
      };
  items?:
    | T
    | {
        text?: T;
        image?: T;
        id?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto_select".
 */
export interface ManifestoSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?:
    | T
    | {
        bright?: T;
        dim?: T;
      };
  subtext?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  backgroundImage?: T;
  portrait?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marquee_select".
 */
export interface MarqueeSelect<T extends boolean = true> {
  words?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-it-works_select".
 */
export interface HowItWorksSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?:
    | T
    | {
        accent?: T;
        rest?: T;
      };
  subtext?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  steps?:
    | T
    | {
        stepLabel?: T;
        title?: T;
        body?: T;
        image?: T;
        imageOverlay?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-afters_select".
 */
export interface BeforeAftersSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?:
    | T
    | {
        accent?: T;
        rest?: T;
      };
  subtext?: T;
  cards?:
    | T
    | {
        name?: T;
        quote?: T;
        signedBy?: T;
        gdc?: T;
        beforeImage?: T;
        afterImage?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?:
    | T
    | {
        accent?: T;
        rest?: T;
      };
  subtext?: T;
  plans?:
    | T
    | {
        title?: T;
        price?: T;
        per?: T;
        productImage?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        buttonLabel?: T;
        variant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  ratingCount?: T;
  heading?:
    | T
    | {
        accent?: T;
        rest?: T;
      };
  viewMoreLabel?: T;
  reviews?:
    | T
    | {
        author?: T;
        timeAgo?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?:
    | T
    | {
        accent?: T;
        rest?: T;
      };
  subtext?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  members?:
    | T
    | {
        name?: T;
        role?: T;
        gdc?: T;
        photo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof_select".
 */
export interface ProofSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?:
    | T
    | {
        accent?: T;
        rest?: T;
      };
  subtext?: T;
  videos?:
    | T
    | {
        thumbnail?: T;
        video?: T;
        videoUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "movers_select".
 */
export interface MoversSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?:
    | T
    | {
        accent?: T;
        rest?: T;
      };
  subtext?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  tiers?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta_select".
 */
export interface CtaSelect<T extends boolean = true> {
  title?: T;
  subtext?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  backgroundImage?: T;
  badge?:
    | T
    | {
        topLabel?: T;
        midLabel?: T;
        bigNumber?: T;
        bottomLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?:
    | T
    | {
        accent?: T;
        rest?: T;
      };
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  mailingLabel?: T;
  emailPlaceholder?: T;
  wordmark?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}